# See https://houndci.com/configuration for help.
fail_on_violations: true
haml:
  # config_file: .haml-style.yml
  enabled: true
javascript:
  # config_file: .javascript-style.json
  enabled: true
  # ignore_file: .javascript_ignore
scss:
  # config_file: .scss-style.yml
  enabled: true
ruby:
  enabled: true
  config_file: .rubocop.yml
coffee_script:
  enabled: true
